[package]
name = "flappy"
version = "0.1.0"
edition = "2018"
author = ["FÃ©lix Rojas <a01201946@tec.mx>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "0.8.1"
